version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - web

volumes:
  postgres_data: